version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: nest-twitter
      POSTGRES_PASSWORD: password
    ports: 
      - '5432:5432'
    volumes:
      - nest-twitter-db:/var/lib/postgresql/data

volumes:
  nest-twitter-db: